### ISSUE TITLE
Adding  i686-w64-mingw32 product to release fails in travis script.

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryBuilder.jl#138]
Log at: https://travis-ci.org/KristofferC/OpenspecfunBuilder/builds/337988666#L1675-L1699

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/KristofferC/OpenspecfunBuilder/releases/9552283/assets?name=openspecfun.i686-w64-mingw32.tar.gz: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:135:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:116:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:107:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:107:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

Don't see anything special in the logs for this product.

**Comment by staticfloat** [comment]
Looks like an HTTP 502 error from the ruby-based file uploader at the end due to a GitHub service barfing.  I don't think there's anything we can do about this; it's just the network being the netdontwork.  :(

**Comment by KristofferC** [comment]
It happens twice in a row with the exact same file.

**Comment by KristofferC** [comment]
I'll make a new release to see if it happens again.

**Comment by KristofferC** [comment]
Worked fine for this release.
